### ISSUE TITLE
Rod issues

### ISSUE THREAD

**Issue by vespersland** [grvyscale/RealtimeOvertrainingDetection#1]
Hi nice project,but i still have several issues.
Rod only works for me by select 1 as iterations at the end of training and gives me a value that often hasn't even been reached based on the number of epochs and the log folder is still empty. Launch - tensorboard.bat it does not work I had to modify with this string python -m  tensorboard.main --logdir logs --bind_all

Thanks in advance for your help

**Comment by grvyscale** [comment]
> Hi nice project,but i still have several issues. Rod only works for me by select 1 as iterations at the end of training and gives me a value that often hasn't even been reached based on the number of epochs and the log folder is still empty. Launch - tensorboard.bat it does not work I had to modify with this string python -m tensorboard.main --logdir logs --bind_all
> 
> Thanks in advance for your help

Can I get ur discord?

**Comment by vespersland** [comment]
> > Hi nice project,but i still have several issues. Rod only works for me by select 1 as iterations at the end of training and gives me a value that often hasn't even been reached based on the number of epochs and the log folder is still empty. Launch - tensorboard.bat it does not work I had to modify with this string python -m tensorboard.main --logdir logs --bind_all
> > Thanks in advance for your help
> 
> Can I get ur discord?
of course 
coverz_66619

**Comment by grvyscale** [comment]
> > > Hi nice project,but i still have several issues. Rod only works for me by select 1 as iterations at the end of training and gives me a value that often hasn't even been reached based on the number of epochs and the log folder is still empty. Launch - tensorboard.bat it does not work I had to modify with this string python -m tensorboard.main --logdir logs --bind_all
> > > Thanks in advance for your help
> > 
> > 
> > Can I get ur discord?
> > of course
> > coverz_66619

mine is same as on github
grvyscale
